### PR TITLE
feat: update icons to v1.4

### PR DESCRIPTION
**Pull request by Joeao**
This change adds all icons that were introduced in https://github.com/phosphor-icons/phosphor-home/releases/tag/v1.4.0.

My process was as follows:
- Emptied existing `svgs` directory
- Copied contents of [release v1.4](https://github.com/phosphor-icons/phosphor-home/releases/tag/v1.4.0) `SVGs`directory into this repo's `svg` directory
- Ran `npm run generate`
- Ran `npm run prepare` for local testing
- Copied new lib into `node_modules` for local testing

If there's nothing more to the process, then it's ready for usage. Otherwise please give feedback and I'll make changes where necessary.

### CODE REVIEW

**Comment by duongdev** [comment]
Hey @Joeao did you try to use the new icons in the example app to make sure every icon is working properly?

**Comment by Joeao** [comment]
I didn't use all the icons, just one actually. I'll implement more of the new icons into the app as part of the self-review, will report my findings.

**Comment by Joeao** [comment]
I'm happy with it

**Review by duongdev — APPROVED** [review]
Thank you for your contribution!

**Comment by duongdev** [comment]
Hey @Joeao, your changes have been released on [v1.1.0](https://github.com/duongdev/phosphor-react-native/releases/tag/v1.1.0). Thanks for your help!

**Pull request merged**
