### PR TITLE
feat: support `mirror` prop

### PR DESCRIPTION
**Pull request by kingdavidmartins**
354ffb312cb4af0a73c118f57d08c08456c9f9c0 - contains the changes for mirrored

### CODE REVIEW

**Comment by kingdavidmartins** [comment]
Once approved will run `node generator/generate-svg.js` let me know if I should run this command or another command? seems like when I run it prettier is not applied? My guess is the pre commit hook should run but it is not at least for me

**Comment by duongdev** [comment]
Hey @kingdavidmartins, thank you for your contribution. Appreciated.

In order to generate new code, you can run `yarn generate` (or `npm run generate`). I have added the `yarn format` script that helps you to format the generated code.

After that, could you please run the mirror icons in the example and put a screenshot here? So I can approve quickly.

By the way, please update the `README.md` to help other users know that we had `mirror` supported.

Thanks!! 🥳

**Comment by kingdavidmartins** [comment]
https://user-images.githubusercontent.com/10181183/145603858-09fe9212-9348-4028-ae39-7d3a9d4b53ff.mov

Updated Example and added example usage in README

**Comment by kingdavidmartins** [comment]
@duongdev Let me know if there is anything else I need to do for this to get a ✅

**Comment by duongdev** [comment]
@kingdavidmartins It seems you didn't run prettier for the generated tsx files or the formatter didn't work properly. Please try formatting the generated code.

image

**Comment by kingdavidmartins** [comment]
@duongdev updated. Prettified 😇

**Comment by kingdavidmartins** [comment]
@duongdev I also added 32b274f since this was the reason why the diff was not showing, per prettier docs the `--write` flag to format a file in-place

**Comment by kingdavidmartins** [comment]
@duongdev bumping

**Review by duongdev — APPROVED** [review]
Great job @kingdavidmartins. So happy that you helped me to have `mirror` implemented. Thanks a lot 🎉

**Pull request merged**
